"""Layer 2 — Obsidian vault writer. Produces Dataview-compatible markdown notes."""
from __future__ import annotations

import logging
import textwrap
from datetime import date, datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class ObsidianVault:
    """Writes markdown notes into an Obsidian vault directory tree."""

    def __init__(self, vault_root: str | Path):
        self._root = Path(vault_root)

    # ------------------------------------------------------------------
    # Stock card  →  Stocks/TICKER.md
    # ------------------------------------------------------------------

    def write_stock_note(
        self,
        ticker: str,
        trade_date: str,
        signal: str,
        confidence: int,
        cs: dict,                  # computed signals dict from india_report
        arbitration_narrative: str = "",
    ):
        base = ticker.replace(".NS", "").replace(".BO", "")
        path = self._root / "Stocks" / f"{base}.md"
        price   = cs.get("price", "N/A")
        sma50   = cs.get("sma50", "N/A")
        rsi     = cs.get("rsi", "N/A")
        macd    = "Bullish" if cs.get("macd_bullish") else "Bearish"
        trend   = "Above 50-SMA" if cs.get("price_above_sma50") else "Below 50-SMA"
        content = textwrap.dedent(f"""\
            ---
            ticker: {base}
            signal: {signal}
            confidence: {confidence}
            last_updated: {trade_date}
            price: {_fmt(price)}
            sma50: {_fmt(sma50)}
            rsi: {_fmt(rsi)}
            macd: {macd}
            trend: {trend}
            tags: [stock, india, nse]
            ---

            # {base} — Trading Intelligence

            **Signal**: {signal} | **Confidence**: {confidence}%
            **Last Updated**: {trade_date}

            ## Technical Snapshot
            | Metric | Value |
            |--------|-------|
            | Price | ₹{_fmt(price)} |
            | 50-SMA | ₹{_fmt(sma50)} |
            | RSI (14) | {_fmt(rsi)} |
            | MACD | {macd} |
            | Trend | {trend} |

            ## Signal Arbitration
            {arbitration_narrative or "_No arbitration data_"}

            ## Decision History
            See [[Decisions/{base}]]
        """)
        _write(path, content)

    # ------------------------------------------------------------------
    # Decision note  →  Decisions/TICKER_DATE.md
    # ------------------------------------------------------------------

    def write_decision_note(
        self,
        ticker: str,
        trade_date: str,
        signal: str,
        confidence: int,
        arbitration_narrative: str,
        final_body: str,
        tech_signal: str = "",
        fund_signal: str = "",
        macro_signal: str = "",
        pm_signal: str = "",
    ):
        base = ticker.replace(".NS", "").replace(".BO", "")
        filename = f"{base}_{trade_date}.md"
        path = self._root / "Decisions" / filename
        content = textwrap.dedent(f"""\
            ---
            ticker: {base}
            trade_date: {trade_date}
            signal: {signal}
            confidence: {confidence}
            tech_signal: {tech_signal or "N/A"}
            fund_signal: {fund_signal or "N/A"}
            macro_signal: {macro_signal or "N/A"}
            pm_signal: {pm_signal or "N/A"}
            tags: [decision, india, nse]
            ---

            # {base} Decision — {trade_date}

            **Final Signal**: {signal} | **Confidence**: {confidence}%

            ## Signal Arbitration
            {arbitration_narrative}

            ## Portfolio Manager Decision
            {final_body[:1500] if final_body else "_No decision text_"}

            ---
            *Generated by Kodryx Trading Intelligence*
        """)
        _write(path, content)

    # ------------------------------------------------------------------
    # Sector roll-up  →  Sectors/SECTOR.md
    # ------------------------------------------------------------------

    def write_sector_note(self, sector: str, stocks_data: list[dict]):
        """stocks_data: list of {ticker, signal, confidence, trade_date}"""
        path = self._root / "Sectors" / f"{sector}.md"
        rows = "\n".join(
            f"| [[Stocks/{s['ticker']}]] | {s['signal']} | {s['confidence']}% | {s['trade_date']} |"
            for s in stocks_data
        )
        buys   = sum(1 for s in stocks_data if "BUY"  in s.get("signal", ""))
        sells  = sum(1 for s in stocks_data if "SELL" in s.get("signal", ""))
        holds  = len(stocks_data) - buys - sells
        content = textwrap.dedent(f"""\
            ---
            sector: {sector}
            last_updated: {date.today()}
            buy_count: {buys}
            sell_count: {sells}
            hold_count: {holds}
            tags: [sector, india]
            ---

            # {sector} — Sector Overview

            **BUY**: {buys} | **SELL**: {sells} | **HOLD**: {holds}

            | Ticker | Signal | Confidence | Date |
            |--------|--------|------------|------|
            {rows}
        """)
        _write(path, content)

    # ------------------------------------------------------------------
    # Event / anomaly note  →  Events/DATE_TICKER_TYPE.md
    # ------------------------------------------------------------------

    def write_event_note(
        self,
        ticker: str,
        trade_date: str,
        anomaly_type: str,
        detail: str,
    ):
        base = ticker.replace(".NS", "").replace(".BO", "")
        safe_type = anomaly_type.replace(" ", "_").upper()
        filename = f"{trade_date}_{base}_{safe_type}.md"
        path = self._root / "Events" / filename
        content = textwrap.dedent(f"""\
            ---
            ticker: {base}
            trade_date: {trade_date}
            anomaly_type: {anomaly_type}
            tags: [event, anomaly, india]
            ---

            # Event: {anomaly_type} — {base} ({trade_date})

            {detail}
        """)
        _write(path, content)

    # ------------------------------------------------------------------
    # Daily brief  →  Daily/DATE.md
    # ------------------------------------------------------------------

    def write_daily_brief(self, trade_date: str, runs: list[dict]):
        """runs: list of {ticker, signal, confidence}"""
        path = self._root / "Daily" / f"{trade_date}.md"
        rows = "\n".join(
            f"| [[Stocks/{r['ticker']}]] | {r['signal']} | {r['confidence']}% |"
            for r in runs
        )
        buys  = sum(1 for r in runs if "BUY"  in r.get("signal", ""))
        sells = sum(1 for r in runs if "SELL" in r.get("signal", ""))
        content = textwrap.dedent(f"""\
            ---
            date: {trade_date}
            total_stocks: {len(runs)}
            buy_signals: {buys}
            sell_signals: {sells}
            tags: [daily-brief, india]
            ---

            # Daily Brief — {trade_date}

            **Stocks Analysed**: {len(runs)} | **BUY**: {buys} | **SELL**: {sells}

            | Ticker | Signal | Confidence |
            |--------|--------|------------|
            {rows}

            ---
            *Kodryx Trading Intelligence — auto-generated*
        """)
        _write(path, content)


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _fmt(v) -> str:
    if v is None or v == "N/A":
        return "N/A"
    try:
        return f"{float(v):,.2f}"
    except Exception:
        return str(v)


def _write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    logger.debug("Obsidian note written: %s", path)
